Add authorization implementation
trakx/fireblocks-api-client pull request #2
Opened 2020-12-30 11:36 UTC by AymericNoel

For the moment, I got an error in integration test : 403 unauthorized.
And I need to do more tests !

2021-01-19 13:35 UTC, monsieurleberre requested changes
It is looking good 😎
Can you add a bit more tests on the JWT content please, and not downgrade libraries?
👍

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/ApiClients.Partials.tt
> +var clientNames = new [] { "FireblocksClient" };
did you not manage to have more than 1 client ?

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/ApiClients.Partials.tt
> +var clientNames = new [] { "FireblocksClient" };
https://github.com/RicoSuter/NSwag/blob/856c75662cb1954d4191ea37b3d14b365bce4561/src/NSwag.Commands/Commands/CodeGeneration/OperationGenerationMode.cs

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/AuthorisedClient.cs
>          {
OK if we don't need to switch api URL between dev and prod, otherwise, it would be better to make it changeable

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/ClientRegistrations.cs
>              var delay = Backoff.DecorrelatedJitterBackoffV2(medianFirstRetryDelay: TimeSpan.FromMilliseconds(100), retryCount: 10, fastFirst: true);
i have noticed retry count = 10 was good for the deployment of the exchange we have at the moment, but for something that should work it is too much. I think I made this configurable in another repo, but you can maybe just set it lower in code here for now

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/FireblocksApiConfiguration.cs
> +
can you add the SecretEnvVariable attribute here from https://github.com/trakx/dotnet-utils/blob/dev/src/Trakx.Utils/Attributes/SecretEnvironmentVariableAttribute.cs

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/Trakx.Fireblocks.ApiClient.csproj
> +    <PackageReference Include="NSwag.MSBuild" Version="13.9.2">
looks like a downgrade

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/Trakx.Fireblocks.ApiClient.csproj
> +    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="3.1.9" />
downgrade?

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/Trakx.Fireblocks.ApiClient.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.9" />
...

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/Utils/BearerCredentialsProvider.cs
> +    public class BearerCredentialsProvider : IBearerCredentialsProvider
please can you seal that in a test where you get a random api key, a random private key, and a random content to encode, and check that the JWT is what you aimed to compute?
when the integration tests stops working, we need to know that someone didn't mess up the authorisation part for instance
If this is not enough to encode the specification that you only discoverd by chatting to fireblocks (for instance, the time needs to not be passed in as a string, etc), can you please add tests to seal that logic too?

2021-01-19 13:35 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/nswag.json
> +      "className": "{controller}FireblocksClient",
they are all going to be fireblock clients right? can you try playing with the operationGenerationMode maybe?

2021-01-19 15:26 UTC, AymericNoel commented on src/Trakx.Fireblocks.ApiClient.Tests/Unit/AddFireblocksClientExtensionTests.cs
> +                ApiPrivateKey = "MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBALXu9makTMIVzt5TeI9wfQ1mID9a6RxVoi/OfRu8Km5SM2/zq2W2h9jwa13a2lU4F1UmXLeFVKwpO+AKE/to5V5grg6VOcfSpJrccMU9i0rgN1DaUFIGR5
[Here](https://github.com/trakx/fireblocks-api-client/blob/2e02a424acffd5449e34e6a04057953160dae3c3/src/Trakx.Fireblocks.ApiClient/Utils/BearerCredentialsProvider.cs#L25) we convert base64 to string so yes we don't need a real RSA key but the function ` rsa.ImportPkcs8PrivateKey()` will check the length of the key and other things to verify that it's a real private RSA key, if not then an error is thrown and we can't execute the test...

2021-01-19 15:29 UTC, AymericNoel commented on src/Trakx.Fireblocks.ApiClient/ApiClients.Partials.tt
> +var clientNames = new [] { "FireblocksClient" };
Ahah I have talked about that in the description ! 
In reality, I didn't suceed because `MultipleClientsFromFirstTagAndOperationId` will just generate one client because we don't have tags and  `MultipleClientsFromFirstTagAndPathSegments` will generate one client and *methodname* with put/post/get in the name...

2021-01-19 15:33 UTC, AymericNoel commented on src/Trakx.Fireblocks.ApiClient/AuthorisedClient.cs
>          {
I deliberately didn't do it because the base  url is in the openApi and therefore is updated every time we update our openApi from fireblocks. It was to avoid making a mistake when adding the baseUrl , because if it is more up to date in the openApi anyway, it's because we have to update the openApi...
What do you think ?

2021-01-19 15:41 UTC, AymericNoel commented on src/Trakx.Fireblocks.ApiClient/nswag.json
> +      "className": "{controller}FireblocksClient",
Yes I we had multiple clients... but as we have only one, I told myself that it's better to have a real client name that juste Client and IClient...

2021-01-19 15:42 UTC, AymericNoel commented on src/Trakx.Fireblocks.ApiClient/Utils/BearerCredentialsProvider.cs
> +    public class BearerCredentialsProvider : IBearerCredentialsProvider
Okay I'm on it !

2021-01-19 17:57 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient.Tests/Unit/AddFireblocksClientExtensionTests.cs
> +                ApiPrivateKey = "MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBALXu9makTMIVzt5TeI9wfQ1mID9a6RxVoi/OfRu8Km5SM2/zq2W2h9jwa13a2lU4F1UmXLeFVKwpO+AKE/to5V5grg6VOcfSpJrccMU9i0rgN1DaUFIGR5
perfect then, I shut up 👍

2021-01-19 18:00 UTC, AymericNoel commented
And you agree with codacy ?

2021-01-19 21:28 UTC, monsieurleberre reviewed
still a couple of little things to change please 🙏

2021-01-19 21:28 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient.Tests/Secrets.cs
>          static Secrets()
I just remember there is now a class called `SecretProvider<T>` that could be used here instead I think
I modified it in 0.1.11 so that it supports not passing in the variable name in the attribute if not needed

2021-01-19 21:28 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient.Tests/Unit/ApiKeyCredentialsProviderTests.cs
> +            _provider.AddCredentials(message);
should we have a test where the message has content before generating the credentials, as it seems like the signature depends on that too right?

2021-01-19 21:28 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/Utils/BearerCredentialsProvider.cs
> +            var body = msg.Content?.ReadAsStringAsync().GetAwaiter().GetResult() ?? string.Empty;
yes it would be good to check we get the good signature for a given content in a test (cf other comment)

2021-01-20 08:20 UTC, AymericNoel commented on src/Trakx.Fireblocks.ApiClient/FireblocksApiConfiguration.cs
> +        [SecretEnvironmentVariable("FireblocksApiConfiguration__ApiSecret")]
https://github.com/trakx/dotnet-utils/blob/959677b298eb25b220761378e0ed90810f212910/src/Trakx.Utils.Testing/EnvFileDocumentationUpdater.cs#L151

Exact !!

2021-01-20 09:15 UTC, AymericNoel commented
The name of the env variables has been changed so wa should change them in github too

2021-01-20 09:16 UTC, AymericNoel commented
`FireblocksApiConfiguration__ApiPrivateKey` and `FireblocksApiConfiguration__ApiPubKey` are the new ones

2021-01-21 16:26 UTC, monsieurleberre approved these changes

2021-01-21 16:28 UTC, monsieurleberre approved these changes

2021-01-22 08:39 UTC, merged