Add namespaces to HttpClients
trakx/fireblocks-api-client pull request #4
Opened 2021-01-27 18:44 UTC by AymericNoel

close #3

2021-01-28 05:24 UTC, monsieurleberre requested changes
let's split the clients again?

2021-01-28 05:24 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/openApi3.yaml
>    #  VAULT
not sure I want this to be mereged 🤔
Yes I remember now I had added that manually, but maybe forgot there was something overriding the file somewhere.

2021-01-28 08:32 UTC, AymericNoel commented
Should be ok by now

2021-01-29 17:34 UTC, monsieurleberre approved these changes
cool thanks 😁👍

2021-01-29 17:34 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/openApi3.yaml
> +  '/vault/assets':
OK I see that is what you had to do manually in the end, that is a pain, we will see how it goes on the long term...

2021-01-29 17:34 UTC, monsieurleberre commented on src/Trakx.Fireblocks.ApiClient/openApi3.yaml
> +  # '/transactions/{txId}/unfreeze':
and this one, why don't we want it?

2021-02-01 15:42 UTC, AymericNoel commented on src/Trakx.Fireblocks.ApiClient/openApi3.yaml
> +  # '/transactions/{txId}/unfreeze':
I have just updated the OpenAPi from fireblocks.... so they are the ones who don't want it anymore 😅

2021-02-01 15:42 UTC, merged